install-uv:
	curl -LsSf https://astral.sh/uv/install.sh | sh


run-pixtral:
	uv run --with ray[serve,llm]>=2.43.0,vllm>=0.7.2

# Suggested dependencies when using vllm 0.7.2:
#pip install xgrammar==0.1.11 pynvml==12.0.0
